import AuthProvider from "@/providers/AuthProvider";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Secured note taking web app",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={ `${geistSans.variable} ${geistMono.variable} antialiased` }
        >
          { children }
          <Toaster position="top-center" />
        </body>
      </AuthProvider>
    </html>
  );
}
